# https://esphome.io/components/rtttl.html

output:
  - platform: ledc
    pin: "${buzzer_pin}"
    id: rtttl_out

api:
  services:
    - service: play_rtttl
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'

rtttl:
  output: rtttl_out
  on_finished_playback:
    - logger.log: 'Song ended!'

esphome:
  on_boot:
    - priority: 10
      then:
        - rtttl.play: "long:d=1,o=5,b=100:e6"
